### ISSUE TITLE
OperationalError While Getting Competitors by Race

### ISSUE THREAD

**Issue by JasonGreenBIT** [JasonGreenBIT/punter-core#45]
While fetching data, the following OperationalError intermittently occurs while getting competitors by race:

(**NOTE:** The error can be worked around by simply running the fetch again!)

Traceback (most recent call last):
  File "/home/jason/.local/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 1193, in _execute_context
    context)
  File "/home/jason/.local/lib/python3.5/site-packages/sqlalchemy/engine/default.py", line 507, in do_execute
    cursor.execute(statement, parameters)
psycopg2.extensions.TransactionRollbackError: deadlock detected
DETAIL:  Process 853 waits for ShareLock on transaction 483079; blocked by process 850.
Process 850 waits for ShareLock on transaction 483077; blocked by process 853.
HINT:  See server log for query details.
CONTEXT:  while updating tuple (12816,10) in relation "performance"

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/jason/.local/lib/python3.5/site-packages/punter_utils/task_thread.py", line 132, in process_race
    competitors = [competitor for competitor in self._provider.get_competitors_by_race(race) if not competitor.is_scratched]
  File "/home/jason/.local/lib/python3.5/site-packages/punter_core/provider.py", line 99, in get_competitors_by_race
    self._db_session.commit()
  File "/home/jason/.local/lib/python3.5/site-packages/sqlalchemy/orm/scoping.py", line 153, in do
    return getattr(self.registry(), name)(*args, **kwargs)
  File "/home/jason/.local/lib/python3.5/site-packages/sqlalchemy/orm/session.py", line 943, in commit
    self.transaction.commit()
  File "/home/jason/.local/lib/python3.5/site-packages/sqlalchemy/orm/session.py", line 467, in commit
    self._prepare_impl()
  File "/home/jason/.local/lib/python3.5/site-packages/sqlalchemy/orm/session.py", line 447, in _prepare_impl
    self.session.flush()
  File "/home/jason/.local/lib/python3.5/site-packages/sqlalchemy/orm/session.py", line 2254, in flush
    self._flush(objects)
  File "/home/jason/.local/lib/python3.5/site-packages/sqlalchemy/orm/session.py", line 2380, in _flush
    transaction.rollback(_capture_exception=True)
  File "/home/jason/.local/lib/python3.5/site-packages/sqlalchemy/util/langhelpers.py", line 66, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/home/jason/.local/lib/python3.5/site-packages/sqlalchemy/util/compat.py", line 187, in reraise
    raise value
  File "/home/jason/.local/lib/python3.5/site-packages/sqlalchemy/orm/session.py", line 2344, in _flush
    flush_context.execute()
  File "/home/jason/.local/lib/python3.5/site-packages/sqlalchemy/orm/unitofwork.py", line 391, in execute
    rec.execute(self)
  File "/home/jason/.local/lib/python3.5/site-packages/sqlalchemy/orm/unitofwork.py", line 556, in execute
    uow
  File "/home/jason/.local/lib/python3.5/site-packages/sqlalchemy/orm/persistence.py", line 177, in save_obj
    mapper, table, update)
  File "/home/jason/.local/lib/python3.5/site-packages/sqlalchemy/orm/persistence.py", line 768, in _emit_update_statements
    execute(statement, multiparams)
  File "/home/jason/.local/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 948, in execute
    return meth(self, multiparams, params)
  File "/home/jason/.local/lib/python3.5/site-packages/sqlalchemy/sql/elements.py", line 269, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/home/jason/.local/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 1060, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/home/jason/.local/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 1200, in _execute_context
    context)
  File "/home/jason/.local/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 1413, in _handle_dbapi_exception
    exc_info
  File "/home/jason/.local/lib/python3.5/site-packages/sqlalchemy/util/compat.py", line 203, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/home/jason/.local/lib/python3.5/site-packages/sqlalchemy/util/compat.py", line 186, in reraise
    raise value.with_traceback(tb)
  File "/home/jason/.local/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 1193, in _execute_context
    context)
  File "/home/jason/.local/lib/python3.5/site-packages/sqlalchemy/engine/default.py", line 507, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (psycopg2.extensions.TransactionRollbackError) deadlock detected
DETAIL:  Process 853 waits for ShareLock on transaction 483079; blocked by process 850.
Process 850 waits for ShareLock on transaction 483077; blocked by process 853.
HINT:  See server log for query details.
CONTEXT:  while updating tuple (12816,10) in relation "performance"
 [SQL: 'UPDATE performance SET trainer_url=%(trainer_url)s WHERE performance.id = %(performance_id)s'] [parameters: {'performance_id': 343713, 'trainer_url': 'https://www.punters.com.au/trainers/kelly-schweida_5/'}] (Background on this error at: http://sqlalche.me/e/e3q8)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/jason/.local/bin/punter", line 11, in <module>
    sys.exit(main())
  File "/home/jason/.local/lib/python3.5/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/jason/.local/lib/python3.5/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/jason/.local/lib/python3.5/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/jason/.local/lib/python3.5/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/jason/.local/lib/python3.5/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/jason/.local/lib/python3.5/site-packages/punter_utils/cli.py", line 68, in fetch
    raise task_queue.exception
  File "/home/jason/.local/lib/python3.5/site-packages/punter_utils/task_thread.py", line 78, in run
    target(*args, **kwargs)
  File "/home/jason/.local/lib/python3.5/site-packages/punter_utils/task_thread.py", line 138, in process_race
    raise Exception('Unable to process {race}'.format(race=race)) from exception
Exception: Unable to process race 4 at Doomben on 08/18/17

**Comment by JasonGreenBIT** [comment]
This is NOT fixed in #46 :(

**Comment by JasonGreenBIT** [comment]
This is still NOT fixed in #47 :(
